### ISSUE TITLE
Erreur sur le logo ou bien c'est intentionnel?

### ISSUE THREAD

**Issue by monkeyK1n9** [ln-dev7/camerenerve#11]
Le logo n'est pas CamerEnerve?

Faudrait revoir le logo?

![image](https://user-images.githubusercontent.com/91855362/234247503-dd0b0b6f-0ae0-4716-beac-628888b818b4.png)

**Comment by ln-dev7** [comment]
Yes c'est bien ca, merci
je vais fix
